site_name: The Materials Project Workshop
site_description: Lessons for the Materials Project Workshop
copyright: Built by The Materials Project
site_url: https://workshop.materialsproject.org
repo_url: https://github.com/materialsproject/workshop
docs_dir: workshop
extra_css: 
  - assets/workshop.css
extra_javascript:
  - assets/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme:
  name: 'material'
  palette:
    primary: blue grey
  logo: assets/materials_project_logo_white.svg
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant
    - tabs

nav:
  - Home: index.md
  - Logistics: logistics/logistics.md
  - People: people/people.md
  - Code of Conduct: code_of_conduct.md
  - Primer:
    - Intro: primer/01_basic_python/0 - Introduction and Jupyter Use.ipynb
    - Basic Python: primer/01_basic_python/1 - Python Primer.ipynb
    - Advanced Python: primer/02_building_logic/2 - Python Primer - Part II.ipynb
    - Intro to MongoDB: primer/03_MongoDB_part1/lessons.ipynb
    - Advanced MongoDB: primer/04_MongoDB_part2/lesson.ipynb
  - Workshop:
    - Day 1:
      - The Materials Project Website: lessons/01_website_walkthrough/website_walkthrough.md
      - Intro to Pymatgen: lessons/02_intro_pymatgen/1 - pymatgen foundations.ipynb
      - Working with Surfaces: lessons/03_surfaces/Working With Surfaces_lesson.ipynb
      - The Materials API: lessons/04_materials_api/api_use.ipynb
    - Day 2:
      - Automated DFT: lessons/05_automated_dft/Lesson.ipynb
      - Exploring New Systems: lessons/06_new_systems/06 - New Systems - filled.ipynb
      - MPContribs: lessons/07_mpcontribs/contribute.ipynb
      - Machine Learning with MatMiner: lessons/08_ml_matminer/matminer-notes.ipynb

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search:
      prebuild_index: true
  - mknotebooks
  - minify:
      minify_html: true
